[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

# Add specific routes for Pinterest API endpoints
[[redirects]]
  from = "/.netlify/functions/pinterest/auth"
  to = "/.netlify/functions/pinterest"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/pinterest/boards"
  to = "/.netlify/functions/pinterest"
  status = 200
  force = true